---
 - name: install pre-install for mail server
   hosts: gpahosts
   remote_user: root
   become_method: sudo
   become_user: root
   vars:
     http_port: 80 
     http_clients: 200 
       
   tasks:
   - name: Update repositories cache and install "make" package
     apt:
       name: ksh
       update_cache: yes
   - name: Update repositories cache and install "rpm" package
     apt:
       name: rpm
       update_cache: yes

   - name: Copy file with owner and permissions
     copy:
        src: /tmp/gpa-0.0.1-SNAPSHOT20210503224207.x86_64.rpm
        dest: /tmp/gpa-0.0.1-SNAPSHOT20210503224207.x86_64.rpm
        owner: root
        group: root
        mode: '064'

   - name: Add the user 'gpaadmin' with a specific uid and a primary group of 'gpaadming'
     user:
        name: gpasdmin
        comment: Global Product Admin
        uid: 1040
        group: gpaadming
   - name: uninstall package.
     shell: rpm -ehv gpa
     args:
       warn: false 
     ignore_errors: yes
     register: services_list

   - name: Install package.
     shell: rpm -ihv /tmp/gpa-0.0.1-SNAPSHOT20210503224207.x86_64.rpm
     args:
       warn: false 
     register: services_list
