---
 - name: install pre-install for mail server
   hosts: local
   remote_user: root
   become_method: sudo
   become_user: root
   vars:
     http_port: 80 
     http_clients: 200 
       
   tasks:
   - name: Update repositories cache and install "make" package
     apt:
       name: make
       update_cache: yes

   - name: Update repositories cache and install "nodejs" package
     apt:
       name: nodejs
       update_cache: yes

   - name: Update repositories cache and install "npm" package
     apt:
       name: npm
       update_cache: yes

   - name: git checkout "wetty" Ampule
     become: True
     git: 
        repo: https://github.com/heaerie/wetty.git
        clone: yes
        update: no
        dest: /root/wetty/

   - name: run the "npm install" at "/root/wetty/"
     shell:
        cmd: npm install
        chdir: /root/wetty/

   - name: run the "start" at "/root/wetty/"
     shell:
        cmd: /root/wetty/start.sh
        chdir: /root/wetty/
