---
   tasks:
   - name: Creates directory
     file:
                path: /home/cassandra
                state: directory
                owner: cassandra 
                group: cassandra 
                mode: 0775
                recurse: yes
   - name: Add the user 'cassandra' with a specific uid and a primary group of 'cassandra'
     user:
                name: cassandra
                comment: John Doe
                uid: 1040
                group: admin
   - name: clone code for cassandra 
     git:
            repo: git@github.com:mylogin/hello.git
            dest: /home/mylogin/hello
