---
 - name: install pre-install for mail server
   hosts: web
   remote_user: root
   become_method: sudo
   become_user: root
   vars:
     http_port: 80 
     http_clients: 200 
       
   tasks:
   - name: add repository  
     command: echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
       update_cache: yes

   - name: install mongodb 
     apt:
       name: mongodb-server
       update_cache: yes

